version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: terraform
    directory: /templates/aws/vpc
    schedule:
      interval: monthly

  - package-ecosystem: terraform
    directory: /templates/aws/static-website
    schedule:
      interval: monthly

  - package-ecosystem: terraform
    directory: /templates/azure/vnet
    schedule:
      interval: monthly
