version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: terraform
    directory: /templates/aws/vpc
    schedule:
      interval: monthly

  - package-ecosystem: terraform
    directory: /templates/aws/static-website
    schedule:
      interval: monthly

  - package-ecosystem: terraform
    directory: /templates/aws/ecs-fargate-service
    schedule:
      interval: monthly

  - package-ecosystem: terraform
    directory: /templates/aws/rds-postgresql
    schedule:
      interval: monthly

  - package-ecosystem: terraform
    directory: /templates/aws/lambda-api
    schedule:
      interval: monthly

  - package-ecosystem: terraform
    directory: /templates/aws/sqs-queue
    schedule:
      interval: monthly

  - package-ecosystem: terraform
    directory: /templates/aws/sns-topic
    schedule:
      interval: monthly

  - package-ecosystem: terraform
    directory: /templates/aws/dynamodb-table
    schedule:
      interval: monthly

  - package-ecosystem: terraform
    directory: /templates/aws/ecr-repository
    schedule:
      interval: monthly

  - package-ecosystem: terraform
    directory: /templates/aws/secrets-manager-secret
    schedule:
      interval: monthly

  - package-ecosystem: terraform
    directory: /templates/azure/vnet
    schedule:
      interval: monthly

  - package-ecosystem: terraform
    directory: /templates/azure/static-website
    schedule:
      interval: monthly

  - package-ecosystem: terraform
    directory: /templates/azure/container-apps
    schedule:
      interval: monthly

  - package-ecosystem: terraform
    directory: /templates/azure/postgresql-flexible
    schedule:
      interval: monthly

  - package-ecosystem: terraform
    directory: /templates/azure/functions-http
    schedule:
      interval: monthly

  - package-ecosystem: terraform
    directory: /templates/azure/service-bus-queue
    schedule:
      interval: monthly

  - package-ecosystem: terraform
    directory: /templates/azure/event-grid-topic
    schedule:
      interval: monthly

  - package-ecosystem: terraform
    directory: /templates/azure/container-registry
    schedule:
      interval: monthly

  - package-ecosystem: terraform
    directory: /templates/azure/key-vault
    schedule:
      interval: monthly
